# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: echo "fabric.secret=$FABRIC_SECRET" >> local.properties
- script: echo "fabric.key=$FABRIC_KEY" >> local.properties

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'detekt ktlint lintDevDebug spotlessKotlinCheck testDevDebugUnitTest'
